name: PR Comment Sanitizer
description: Rewrites offensive PR review comments using OpenAI and GitHub API
author: ravikiran763

inputs:
  token:
    description: GitHub token to access PR review comments
    required: true
  openaiApiKey:
    description: OpenAI API key to rewrite comments
    required: true
  pr:
    description: Pull request number to sanitize
    required: true
  repo:
    description: full repository name (e.g., owner/repo)
    required: true

runs:
  using: node20
  main: dist/cli.js
