name: PR Sanitizer
on:
  pull_request_review:
    types: [submitted, edited]
jobs:
  sanitize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run PR Sanitizer
        uses: ./ 
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
